# fly.toml file generated for jbsy on 2022-12-28T17:35:11+08:00

app = "jbsy"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "5000"
  LINE_ACCESS_TOKEN = "JjDWKOwxJ6Cwg4L4mQ/RnJv0CgQdYMvFCKa6ayqUMzgRqa7ZufWnVbkW/zuW0hjXxzWFpjE3nk3XpyJ6qhrjvljczlO+7wpTq7oKjZTGUQCIYFe2z3fy2pCP3beUC6jzJfoqSLVxp3hGJW99tqE9BQdB04t89/1O/w1cDnyilFU="
  LINE_CHANNEL_SECRET = "c58ae1cb241fbac4858f26fef7c94a9c"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
